/**
 * The *shape* of the sequence — stanza line counts per movement — used to generate
 * placeholder text. Counts are approximations of the printed poem (the real text is
 * never stored here); they only need to be realistic enough to exercise layout,
 * navigation, scenes and visualizations.
 *
 * Each stanza entry is a line count, optionally with decorations:
 *   { n: 15, indent: [[3, 8]] }  → lines 3 and 8 of the stanza indented 8 spaces
 *   { n: 12, step: [5] }         → line 5 of the stanza is a stepped (dropped) line
 */
import type { QuartetId } from "../model";

export interface StanzaShape {
  n: number;
  indent?: Array<[line: number, spaces: number]>;
  step?: number[];
}
export type MovementShape = StanzaShape[];

export interface QuartetShape {
  id: QuartetId;
  code: string;
  title: string;
  /** Front matter placeholder lines, blank-line separated paragraphs. */
  front: string[][];
  movements: [MovementShape, MovementShape, MovementShape, MovementShape, MovementShape];
}

const s = (n: number, extra: Omit<StanzaShape, "n"> = {}): StanzaShape => ({ n, ...extra });

export const SAMPLE_SHAPE: QuartetShape[] = [
  {
    id: "burnt-norton",
    code: "BN",
    title: "BURNT NORTON",
    front: [
      ["BN front matter 1 — placeholder · λόγος"],
      ["BN front matter 2 — placeholder · ὁδὸς"],
    ],
    movements: [
      [s(10), s(36, { step: [4, 21] })],
      [s(15, { indent: [[13, 4]] }), s(17), s(11)],
      [s(26, { step: [9] }), s(16, { indent: [[1, 6], [2, 6]] })],
      [s(10, { indent: [[2, 4], [5, 8], [6, 8]] })],
      [s(22, { step: [12] }), s(17)],
    ],
  },
  {
    id: "east-coker",
    code: "EC",
    title: "EAST COKER",
    front: [],
    movements: [
      [s(13), s(10), s(23, { indent: [[6, 4], [7, 4], [8, 4]] }), s(5)],
      [s(17), s(11, { step: [3] }), s(20)],
      [s(22), s(13), s(15, { indent: [[3, 4], [4, 4], [5, 4], [6, 4], [7, 4], [8, 4]] })],
      [s(5), s(5), s(5), s(5), s(5)],
      [s(18, { step: [7] }), s(20)],
    ],
  },
  {
    id: "the-dry-salvages",
    code: "DS",
    title: "THE DRY SALVAGES",
    front: [["DS front matter 1 — placeholder", "DS front matter 2 — placeholder", "DS front matter 3 — placeholder"]],
    movements: [
      [s(14), s(35, { step: [18] })],
      [s(6), s(6), s(6), s(6), s(6), s(6), s(18), s(13)],
      [s(13), s(17, { indent: [[4, 4], [5, 4], [6, 4]] }), s(18)],
      [s(5), s(5), s(5)],
      [s(18), s(14, { step: [6] }), s(18)],
    ],
  },
  {
    id: "little-gidding",
    code: "LG",
    title: "LITTLE GIDDING",
    front: [],
    movements: [
      [s(20), s(19, { step: [8] }), s(16)],
      [s(8), s(8), s(8), s(72)],
      [s(16), s(18, { indent: [[2, 4], [3, 4], [4, 4]] })],
      [s(7), s(7)],
      [s(22, { step: [15] }), s(1), s(22)],
    ],
  },
];

const ROMAN = ["I", "II", "III", "IV", "V"];

/** Render a shape as a plain-text source file in the importer's input format. */
export function renderSampleSource(q: QuartetShape): string {
  const out: string[] = [
    "%% still-point sample text — placeholder lines only, generated by scripts/make-sample.ts",
    "%% edition: sample (shape approximates the printed sequence)",
    q.title,
    "",
  ];
  for (const para of q.front) {
    out.push(...para, "");
  }
  q.movements.forEach((mv, mi) => {
    out.push(ROMAN[mi]!, "");
    let n = 0;
    mv.forEach((st) => {
      for (let i = 1; i <= st.n; i++) {
        n++;
        const text = `${q.code}.${mi + 1} line ${n} — placeholder`;
        const ind = st.indent?.find(([l]) => l === i)?.[1] ?? 0;
        if (st.step?.includes(i)) {
          out.push("%% step", " ".repeat(24) + text);
        } else {
          out.push(" ".repeat(ind) + text);
        }
      }
      out.push("");
    });
  });
  return out.join("\n");
}
